### ISSUE TITLE
Uno UWP Issue

### ISSUE THREAD

**Issue by MelbourneDeveloper** [krdmllr/DotNetDesktopSamples#1]
I get this when I try to build:

![image](https://user-images.githubusercontent.com/16697547/80851196-7c1abf00-8c63-11ea-8354-2e79164ca0de.png)

>Severity	Code	Description	Project	File	Line	Suppression State
Error		Validation error. error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 57, Reason: 'MyCompany' violates pattern constraint of '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*'. The attribute 'Publisher' with value 'MyCompany' failed to parse.	Uno.Uwp	C:\Code\DotNetDesktopSamples\Uno\Uno.UWP\bin\x86\Debug\AppxManifest.xml

**Comment by krdmllr** [comment]
UWP requires a signing certificate which you would generate with your company information, I pushed a test certificate :)
